//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string Director { get; set; }
        public decimal Gross { get; set; }
        public double Rating { get; set; }
        public int GenreID { get; set; }
    
        public virtual Genre Genre { get; set; }
    }
}
